import { LocaleConfig } from 'ngx-daterangepicker-bootstrap';

export const DatePickerLocaleConfig: Record<string, LocaleConfig> = {
  en: {
    format: 'DD MMM YYYY',
    firstDay: 1,
    applyLabel: 'Apply',
    cancelLabel: 'Cancel',
    daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    monthNames: [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ],
  },

  ar: {
    format: 'DD MMM YYYY',
    firstDay: 6,
    applyLabel: 'تطبيق',
    cancelLabel: 'إلغاء',
    daysOfWeek: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
    monthNames: [
      'يناير',
      'فبراير',
      'مارس',
      'أبريل',
      'مايو',
      'يونيو',
      'يوليو',
      'أغسطس',
      'سبتمبر',
      'أكتوبر',
      'نوفمبر',
      'ديسمبر',
    ],
  },

  mr: {
    format: 'DD MMM YYYY',
    firstDay: 1,
    applyLabel: 'लागू करा',
    cancelLabel: 'रद्द करा',
    daysOfWeek: ['र', 'सो', 'मं', 'बु', 'गु', 'शु', 'श'],
    monthNames: [
      'जानेवारी',
      'फेब्रुवारी',
      'मार्च',
      'एप्रिल',
      'मे',
      'जून',
      'जुलै',
      'ऑगस्ट',
      'सप्टेंबर',
      'ऑक्टोबर',
      'नोव्हेंबर',
      'डिसेंबर',
    ],
  },
};
